common_args:
  training_type: "simulation"
  random_seed: 0

data_args:
  dataset: "cifar10"
  data_cache_dir: ~/.cache/fedml_data
  partition_method: "homo"
  partition_alpha: 0.5

model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 50
  comm_round: 1500
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.1
  weight_decay: 0.0

validation_args:
  frequency_of_the_test: 10

# Single process
device_args:
  using_gpu: true
  gpu_id: 0
comm_args:
  backend: "sp"
  is_mobile: 0


tracking_args:
   # When running on MLOps platform(open.fedml.ai), the default log path is at ~/.fedml/fedml-client/fedml/logs/ and ~/.fedml/fedml-server/fedml/logs/
  enable_wandb: false

attack_args:
  enable_attack: false
  attack_type: None

defense_args:
  enable_defense: false
