name: 'Full Install'
description: 'Install dependencies using Poetry with optional extras'

inputs:
  extras:
    description: 'Space-separated list of extras to install (e.g., "tf pytorch trees")'
    required: false
    default: 'tf pytorch trees'

runs:
  using: 'composite'
  steps:
    - name: Create extras file for cache key
      shell: bash
      run: echo "${{ inputs.extras }}" > extras.txt

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'
        cache-dependency-path: |
          poetry.lock
          extras.txt
    
    - name: Install Poetry and configure virtualenv location
      shell: bash
      run: |
        pip install poetry
        poetry config virtualenvs.in-project true
        
    - name: Install dependencies
      shell: bash
      run: |
        poetry install -E "${{ inputs.extras }}" -q || true
        poetry run ./build_scripts/install_horovod.sh "${{ inputs.extras }}" true
