name: 'Benchmark Install'
description: 'Install dependencies for benchmark tests'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      shell: bash
      run: |
        cd benchmarks
        pip install poetry
        poetry install -E tf -E pytorch --no-root || true
        echo "PYTHONPATH=." >> $GITHUB_ENV