name: 'Benchmark Install'
description: 'Install dependencies for benchmark tests'

runs:
  using: 'composite'
  steps:
    - name: Install Poetry
      shell: bash
      # install poetry before python because the setup-python action
      # tries to use poetry to resolve cache configuration
      run: pipx install poetry==1.6.1

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'poetry'

    - name: Install dependencies
      shell: bash
      run: |
        cd benchmarks
        poetry install -E tf -E pytorch --no-root || true
        echo "PYTHONPATH=." >> $GITHUB_ENV