name: Publish Wheel

on:
  push:
    tags:
      - 'v*'

jobs:
  build-wheel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Build the wheel
        run: make build
      - name: Upload python package artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: packages/backend/dist/

  publish-wheel:
    runs-on: ubuntu-22.04
    needs:
      - build-wheel
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/project/pfl/
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: python-dist
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
